# Dataset Parameters
num_classes: 5
# define lebels to class dictionary
labels_to_class:
  0: 'daisy'
  1: 'dandelion'
  2: 'rose'
  3: 'sunflower'
  4: 'tulip'

mean_val: [0.57711623,0.57658564,0.47776383]
std_val: [0.09158824,0.09528065,0.20864842]

#class_to_labels: {'daisy':0,'dandelion':1,'rose':2,'sunflower':3,'tulip':4}

#paths
root_path: 'D:\2020\Trainings\self_supervised_learning'
data_path: 'dataset'
exp_type: 'supervised' # 'supervised' or 'self-supervised'
save_dir: 'sl_rotnet_pret_1'
imgs_dir: 'flowers'
labels_dir: 'annotations'
log: 'train.log'

# Self Supervised Params
pretext: False
num_rot: 4

#supervised params
use_pretrained: False
pretrained_dir: None
pretrained_weights: None

use_ssl: True
ssl_pretrained_exp_path: 'ssl_rotnet'
ssl_weight: 'resnet18_epoch242_checkpoint.pth'

#model parameters
network: 'resnet18'
lr: 1e-3
momentum: 9e-1
scheduler: False
opt: 'adam'

# Training Parameters
num_epochs: 5
batch_size: 16
mean_norm: False
img_sz: 128
val_split: 0.15
cuda_num: 2
use_cuda: False